language: php

php:
  - 7.4
  - 8.0

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer update --no-interaction $PREFER_LOWEST

script:
  - vendor/bin/phpunit

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""
