language: php

php:
  - 7.3
  - 7.4

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer update --no-interaction $PREFER_LOWEST

script:
  - vendor/bin/phpunit

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""
